# Используем официальный образ Python
FROM python:3.12-slim

WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install -r requirements.txt

# Копируем приложение
COPY . .

# Запуск приложения
CMD ["python", "app.py"]